// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urybnfferjyjbmhkrraz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyeWJuZmZlcmp5amJtaGtycmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDAyNDUsImV4cCI6MjA2MDUxNjI0NX0.30VQm1pUpD31tP-FhNSRxes3VLhGlu1AVgKuX-a2y-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);